export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SUCCESS_ALERT = 'SUCCESS_ALERT';


export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';
export const ENTER_CODE = 'ENTER_CODE';
export const GET_TOTAL='GET_TOTAL'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const GET_EXPORT_SUCCESS = 'GET_EXPORT_SUCCESS';
export const GET_EXPORT_BEGIN = 'GET_EXPORT_BEGIN';
export const GET_EXPORT_FAIL = 'GET_EXPORT_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const FORM_SUCCESS = 'FORM_SUCCESS';
export const FORM_FAIL = 'FORM_FAIL';
export const FORM_BEGIN = 'FORM_BEGIN';




export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const HANDLE_MULTIPLE_CHANGES = 'HANDLE_MULTIPLE_CHANGES';
export const CLEAR_VALUES = 'CLEAR_VALUES';


export const GET_RESPONSE_GROUPS_BEGIN = 'GET_RESPONSE_GROUPS_BEGIN';
export const GET_RESPONSE_GROUPS_SUCCESS = 'GET_RESPONSE_GROUPS_SUCCESS';
export const GET_RESPONSE_GROUPS_ERROR = 'GET_RESPONSE_GROUPS_ERROR';

export const PAGE_FULL = 'PAGE_FULL';


export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS';
